# Generated by Django 2.1.2 on 2019-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teaching Candidate'), (2, 'Clinical Supervisor'), (3, 'Challenge Coach'), (4, 'Admin')], null=True),
        ),
    ]
