# Generated by Django 2.0.5 on 2018-11-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photos',
            new_name='photo',
        ),
    ]
