# Generated by Django 2.1.7 on 2019-03-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
