# Generated by Django 2.1.7 on 2019-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teaching Candidate'), (2, 'Clinical Supervisor'), (3, 'Challenge Coach'), (4, 'Admin')], default=1, null=True),
        ),
    ]
