# Generated by Django 2.1.7 on 2019-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190722_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjectMatter',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (1, 'Mathematics'), (2, 'Science'), (3, 'Mathematics & Science'), (4, 'Not Applicable')], default=0, null=True),
        ),
    ]
