# Generated by Django 2.2.5 on 2021-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_subjectmatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Visitor'), (1, 'Teaching Candidate'), (2, 'Evaluator'), (3, 'Challenge Coach'), (4, 'Admin')], default=1, null=True),
        ),
    ]
