# Generated by Django 2.2.5 on 2020-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeListSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaceChallengesMega', models.BooleanField(default=False)),
            ],
        ),
    ]
