# Generated by Django 2.2.5 on 2020-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeListSort',
        ),
    ]
