# Generated by Django 2.2.5 on 2020-03-18 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
        ('account', '0006_profile_subjectmatter'),
        ('centralDispatch', '0002_delete_challengelistsort'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ManyToManyField(blank=True, default='', to='rubrics.Challenge')),
                ('profile', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
