# Generated by Django 2.2.5 on 2020-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0003_solutionrouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrouter',
            name='automate',
            field=models.BooleanField(default=False),
        ),
    ]
