# Generated by Django 2.2.5 on 2020-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0004_solutionrouter_automate'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrouter',
            name='routerChoices',
            field=models.IntegerField(choices=[(1, 'Subject Matter'), (2, 'Challenge Specific'), (3, 'Manually Assign'), (4, 'Legacy Challenge')], null=True),
        ),
    ]
