# Generated by Django 2.2.5 on 2020-03-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
        ('centralDispatch', '0005_solutionrouter_routerchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrouter',
            name='solutionInstance',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance'),
        ),
    ]
