# Generated by Django 2.2.5 on 2020-03-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0006_solutionrouter_solutioninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrouter',
            name='profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
