# Generated by Django 2.2.5 on 2020-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0007_auto_20200324_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrouter',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
