# Generated by Django 2.2.5 on 2020-03-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
        ('account', '0006_profile_subjectmatter'),
        ('centralDispatch', '0008_solutionrouter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAssignmentKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
                ('userSolution', models.ManyToManyField(blank=True, default='', to='rubrics.UserSolution')),
            ],
        ),
    ]
