# Generated by Django 2.2.5 on 2020-03-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_subjectmatter'),
        ('rubrics', '0136_auto_20200302_1232'),
        ('centralDispatch', '0009_manualassignmentkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='coach', to='account.Profile')),
                ('evaluator', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='evaluator', to='account.Profile')),
                ('userSolution', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='rubrics.UserSolution')),
            ],
        ),
        migrations.DeleteModel(
            name='ManualAssignmentKeeper',
        ),
    ]
