# Generated by Django 2.2.5 on 2020-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0012_auto_20200331_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrouter',
            name='routerChoices',
            field=models.IntegerField(blank=True, choices=[(1, 'Subject Matter'), (2, 'Challenge Specific'), (3, 'Manually Assign'), (4, 'Legacy Challenge')], null=True),
        ),
    ]
