# Generated by Django 2.2.5 on 2020-04-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0013_auto_20200403_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrouter',
            name='solutionInstance',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance'),
        ),
    ]
