# Generated by Django 2.2.5 on 2020-04-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centralDispatch', '0015_auto_20200403_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentkeeper',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 2), ('role', 3), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coach', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='assignmentkeeper',
            name='evaluator',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 2), ('role', 3), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluator', to='account.Profile'),
        ),
        migrations.CreateModel(
            name='SomethingHappened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('archivedName', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userSolution', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubrics.UserSolution')),
            ],
        ),
    ]
