# Generated by Django 2.2.5 on 2020-04-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0016_auto_20200414_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somethinghappened',
            name='time',
        ),
    ]
