# Generated by Django 2.2.5 on 2020-04-14 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0017_remove_somethinghappened_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='somethinghappened',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), default=list, size=None),
        ),
    ]
