# Generated by Django 2.2.5 on 2020-04-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0018_somethinghappened_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentkeeper',
            name='userSolution',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),
        migrations.AlterField(
            model_name='somethinghappened',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
