# Generated by Django 2.2.5 on 2020-04-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0021_auto_20200414_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somethinghappened',
            name='user',
        ),
    ]
