# Generated by Django 2.2.5 on 2020-05-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
        ('centralDispatch', '0023_auto_20200414_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeAccepted', models.BooleanField(default=False)),
                ('solutionSubmitted', models.BooleanField(default=False)),
                ('solutionEvaluated', models.BooleanField(default=False)),
                ('solutionCoachReviewed', models.BooleanField(default=False)),
                ('solutionRejected', models.BooleanField(default=False)),
                ('solutionCompleted', models.BooleanField(default=False)),
                ('returnTo', models.IntegerField(blank=True, choices=[(1, 'Evaluator'), (2, 'Coach')], null=True)),
                ('userSolution', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution')),
            ],
        ),
    ]
