# Generated by Django 2.2.5 on 2020-05-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_subjectmatter'),
        ('centralDispatch', '0025_auto_20200506_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatus',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
