# Generated by Django 2.2.5 on 2020-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0029_auto_20200528_1311'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengestatus',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_challenge_status'),
        ),
    ]
