# Generated by Django 2.2.5 on 2020-05-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0030_auto_20200529_1430'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='challengestatus',
            name='unique_challenge_status',
        ),
    ]
