# Generated by Django 2.2.5 on 2020-06-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0137_auto_20200611_1621'),
        ('centralDispatch', '0031_auto_20200529_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstatus',
            name='solutionInstance',
            field=models.ForeignKey(null=True, default='', on_delete=django.db.models.deletion.PROTECT, to='rubrics.SolutionInstance'),
        ),
    ]
