# Generated by Django 2.2.5 on 2020-06-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0032_solutionstatus_solutioninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionInstance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rubrics.SolutionInstance', null=True),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='userSolution',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),
    ]
