# Generated by Django 2.2.5 on 2020-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0039_auto_20200710_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
