# Generated by Django 2.2.5 on 2020-08-27 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0149_auto_20200821_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centralDispatch', '0040_challengestatus_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioExpoChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('learningExpoChoice', models.ManyToManyField(blank=True, default='', to='rubrics.LearningExperience')),
                ('userList', models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
