# Generated by Django 2.2.5 on 2020-08-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centralDispatch', '0042_studioexpochoice_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioexpochoice',
            name='userList',
        ),
        migrations.AddField(
            model_name='studioexpochoice',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
