# Generated by Django 2.2.5 on 2020-10-27 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0044_auto_20200827_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='somethinghappened',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='somethinghappened',
            name='modCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somethinghappened',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
