# Generated by Django 2.2.5 on 2021-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0045_auto_20201027_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionCoachReviewed',
            field=models.BooleanField(default=False, verbose_name='Coach Reviewed'),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionCompleted',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionEvaluated',
            field=models.BooleanField(default=False, verbose_name='Evaluated'),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionRejected',
            field=models.BooleanField(default=False, verbose_name='Needs Revision'),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='solutionSubmitted',
            field=models.BooleanField(default=False, verbose_name='Submitted'),
        ),
    ]
