# Generated by Django 2.2.5 on 2021-06-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0152_megachallenge_collapse'),
        ('centralDispatch', '0046_auto_20210609_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='solutionInstance',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance'),
        ),
    ]
