# Generated by Django 2.2.5 on 2021-07-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0047_emailmessage_solutioninstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='event',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='centralDispatch.EmailEvent'),
        ),
    ]
