# Generated by Django 2.2.5 on 2021-07-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0048_auto_20210706_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='urlPath',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='event',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='centralDispatch.EmailEvent'),
        ),
    ]
