# Generated by Django 2.2.4 on 2022-02-16 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralDispatch', '0049_auto_20210706_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstatus',
            name='returnTo',
            field=models.ForeignKey(blank=True, default='', limit_choices_to=models.Q(profile__role__gte=2), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
