# Generated by Django 2.2.5 on 2021-01-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210115_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='team',
        ),
    ]
