# Generated by Django 2.2.5 on 2021-01-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0151_auto_20210105_1258'),
        ('portfolio', '0003_remove_portfolio_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
            preserve_default=False,
        ),
    ]
