# Generated by Django 2.2.5 on 2021-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='hardDetail',
            field=models.TextField(default='', verbose_name='Which detail shows what was especially hard for you?  how? (*required)'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='proudDetail',
            field=models.TextField(default='', verbose_name='What’s a specific detail in this work that you are especially proud of? why? (*required)'),
        ),
    ]
