# Generated by Django 2.2.5 on 2021-01-15 17:23

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='link',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
