# Generated by Django 2.2.5 on 2021-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0151_auto_20210105_1258'),
        ('portfolio', '0007_userportfolio_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='rubricLines',
            field=models.ManyToManyField(null=True, to='rubrics.RubricLine'),
        ),
    ]
