# Generated by Django 2.2.5 on 2021-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_userportfolio_rubriclines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='rubricLines',
            field=models.ManyToManyField(blank=True, to='rubrics.RubricLine'),
        ),
    ]
