# Generated by Django 2.2.5 on 2021-01-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0151_auto_20210105_1258'),
        ('portfolio', '0009_auto_20210115_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='finalRubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Rubric'),
        ),
    ]
