# Generated by Django 2.2.5 on 2021-02-05 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_tempuserportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuserportfolio',
            name='team',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
