# Generated by Django 2.2.5 on 2020-02-12 20:43

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubrics', '0122_auto_20200205_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('mainText', djrichtextfield.models.RichTextField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('occurrenceDate', models.DateTimeField(default=datetime.datetime(2020, 2, 12, 15, 43, 21, 929603))),
                ('learningExpos', models.ManyToManyField(blank=True, to='rubrics.LearningExperience')),
            ],
        ),
    ]
