# Generated by Django 2.2.5 on 2020-08-28 19:33

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20200828_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='description',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 33, 3, 408679)),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='description',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
