# Generated by Django 2.2.5 on 2020-08-28 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20200828_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 39, 21, 995075)),
        ),
        migrations.RemoveField(
            model_name='discussionboard',
            name='topic',
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='topic',
            field=models.ManyToManyField(blank=True, default='', to='info.DiscussionTopic'),
        ),
    ]
