# Generated by Django 2.2.5 on 2020-08-28 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20200828_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 16, 21, 9, 588806)),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
