# Generated by Django 2.2.5 on 2020-08-28 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20200828_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionboard',
            name='topic',
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.DiscussionBoard'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 16, 34, 16, 464129)),
        ),
    ]
