# Generated by Django 2.2.5 on 2020-08-28 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0149_auto_20200821_1225'),
        ('info', '0014_auto_20200828_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 17, 2, 52, 713470)),
        ),
        migrations.RemoveField(
            model_name='discussionboard',
            name='challenge',
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='challenge',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='rubrics.Challenge'),
        ),
    ]
