# Generated by Django 2.2.5 on 2020-08-28 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20200828_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 17, 9, 8, 764267)),
        ),
    ]
