# Generated by Django 2.2.5 on 2020-08-28 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20200828_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 17, 28, 4, 66921)),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='challenge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rubrics.Challenge'),
        ),
    ]
