# Generated by Django 2.2.5 on 2021-02-03 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20200828_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 13, 50, 16, 158439)),
        ),
    ]
