# Generated by Django 2.2.5 on 2021-04-01 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20210203_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 15, 29, 33, 246939)),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='challenge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
        ),
    ]
