# Generated by Django 2.2.5 on 2021-09-17 15:42

import datetime
from django.db import migrations, models
import djrichtextfield.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('info', '0020_auto_20210401_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('custom', djrichtextfield.models.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 11, 42, 19, 130902)),
        ),
        migrations.CreateModel(
            name='FakeLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compGroup', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('compNumber', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('loNumber', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('name', models.TextField(blank=True, default='')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive (hides LO)')),
                ('questionGroup', models.ManyToManyField(blank=True, to='info.QuestionStub')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
