# Generated by Django 2.2.5 on 2021-09-17 16:07

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20210917_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 12, 7, 5, 390286)),
        ),
        migrations.AlterField(
            model_name='questionstub',
            name='custom',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
