# Generated by Django 2.2.5 on 2021-09-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20210917_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 12, 8, 36, 44841)),
        ),
        migrations.AlterField(
            model_name='questionstub',
            name='custom',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
