# Generated by Django 2.2.5 on 2021-09-17 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20210917_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcontainer',
            name='baseInfo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='info.BaseInfo'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 13, 15, 23, 744256)),
        ),
    ]
