# Generated by Django 2.2.5 on 2021-09-17 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20210917_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 13, 21, 6, 447271)),
        ),
        migrations.CreateModel(
            name='FakeCompetency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakeLos', models.ManyToManyField(blank=True, to='info.FakeLO')),
            ],
        ),
    ]
