# Generated by Django 2.2.5 on 2021-09-17 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20210917_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakecompetency',
            name='name',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 13, 22, 56, 589371)),
        ),
    ]
