# Generated by Django 2.2.5 on 2021-09-17 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20210917_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 15, 0, 53, 38042)),
        ),
    ]
