# Generated by Django 2.2.5 on 2021-09-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_auto_20210917_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstub',
            name='questionCategory',
            field=models.CharField(choices=[('A', 'Elicit'), ('B', 'Go Deeper'), ('C', 'Step Back'), ('D', 'Take Action')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 10, 54, 25, 966739)),
        ),
    ]
