# Generated by Django 2.2.5 on 2021-09-20 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_auto_20210920_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcontainer',
            name='coordinates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 12, 17, 1, 890187)),
        ),
    ]
