# Generated by Django 2.2.5 on 2021-11-01 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0154_temptfjsolution'),
        ('info', '0031_auto_20210921_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstub',
            name='learningObjective',
            field=models.ForeignKey(null=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 12, 7, 2, 38577)),
        ),
    ]
