# Generated by Django 2.2.4 on 2021-11-16 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0032_auto_20211101_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 16, 20, 687982)),
        ),
        migrations.CreateModel(
            name='DjPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField(default=0)),
                ('designJournal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.DesignJournal')),
            ],
        ),
    ]
