# Generated by Django 2.2.4 on 2021-11-16 16:03

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_auto_20211116_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='djpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 11, 3, 33, 746731)),
        ),
    ]
