# Generated by Django 2.2.4 on 2021-11-16 16:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0034_auto_20211116_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='djpage',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='djpage_related', related_query_name='djpage_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 11, 49, 1, 100179)),
        ),
        migrations.CreateModel(
            name='DjPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.CharField(default='', max_length=2000)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='djprompt_related', related_query_name='djprompt_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
