# Generated by Django 2.2.4 on 2021-11-16 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_auto_20211116_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djprompt',
            name='response',
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 12, 8, 51, 709912)),
        ),
        migrations.CreateModel(
            name='DjResponse',
            fields=[
                ('djpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.DjPage')),
                ('prompt', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.DjPrompt')),
            ],
            options={
                'abstract': False,
            },
            bases=('info.djpage',),
        ),
    ]
