# Generated by Django 2.2.4 on 2021-12-01 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_auto_20211116_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcontainer',
            name='highlight',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 9, 4, 18, 576531)),
        ),
    ]
