# Generated by Django 2.2.4 on 2022-02-14 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0040_auto_20220214_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 40, 37, 784621)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
