# Generated by Django 2.2.4 on 2022-02-14 15:50

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0041_auto_20220214_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmoduleresponse',
            name='response',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 50, 1, 349267)),
        ),
    ]
