# Generated by Django 2.2.4 on 2022-02-15 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0042_auto_20220214_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 9, 48, 34, 119584)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.BaseModel')),
                ('messageText', models.TextField(blank=True, default='')),
                ('pageLocation', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='info.LearningModulePage')),
                ('recipient', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('info.basemodel',),
        ),
    ]
