# Generated by Django 2.2.4 on 2022-02-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0043_auto_20220215_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 12, 17, 2, 998808)),
        ),
        migrations.AlterField(
            model_name='learningmoduleprompt',
            name='promptText',
            field=models.TextField(default=''),
        ),
    ]
