# Generated by Django 2.2.4 on 2022-02-16 18:27

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0044_auto_20220215_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodulepage',
            name='prompt',
        ),
        migrations.AddField(
            model_name='learningmodulepage',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 13, 27, 33, 443181)),
        ),
        migrations.RemoveField(
            model_name='learningmodulepage',
            name='content',
        ),
        migrations.CreateModel(
            name='LearningModulePageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionContent', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('prompts', models.ManyToManyField(blank=True, to='info.LearningModulePrompt')),
            ],
        ),
        migrations.AddField(
            model_name='learningmodulepage',
            name='content',
            field=models.ManyToManyField(to='info.LearningModulePageSection'),
        ),
    ]
