# Generated by Django 2.2.4 on 2022-02-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0154_temptfjsolution'),
        ('info', '0045_auto_20220216_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulepagesection',
            name='learningObjectives',
            field=models.ManyToManyField(blank=True, default='', to='rubrics.LearningObjective'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 9, 55, 31, 167782)),
        ),
    ]
