# Generated by Django 2.2.4 on 2022-02-21 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0046_auto_20220221_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 10, 20, 32, 335767)),
        ),
        migrations.CreateModel(
            name='PageOrderThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='info.LearningModulePage')),
                ('sections', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='info.LearningModulePageSection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
