# Generated by Django 2.2.4 on 2022-02-21 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0047_auto_20220221_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulepagesection',
            name='attribution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learningmodulepagesection',
            name='category',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Attributed'), (3, 'Student Work')], default=1),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 11, 11, 46, 616722)),
        ),
    ]
