# Generated by Django 2.2.4 on 2022-02-21 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0049_auto_20220221_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmodulepagesection',
            options={'ordering': ()},
        ),
        migrations.AddField(
            model_name='learningmodulepagesection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 11, 54, 19, 12339)),
        ),
    ]
