# Generated by Django 2.2.4 on 2022-02-21 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0050_auto_20220221_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlearningobjective',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 12, 12, 35, 661464)),
        ),
    ]
