# Generated by Django 2.2.4 on 2022-02-21 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0051_auto_20220221_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlearningobjective',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 13, 3, 22, 914508)),
        ),
    ]
