# Generated by Django 2.2.4 on 2022-03-02 16:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0052_auto_20220221_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModulePromptInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 11, 22, 5, 181235)),
        ),
        migrations.AlterField(
            model_name='learningmoduleresponse',
            name='response',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learningmodulepagesection',
            name='promptInstructions',
            field=models.ManyToManyField(blank=True, to='info.LearningModulePromptInstructions'),
        ),
    ]
