# Generated by Django 2.2.4 on 2022-03-10 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0055_auto_20220310_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmoduleprompt',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='learningmoduleprompt',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='occurrenceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 9, 41, 29, 884531)),
        ),
    ]
