# Generated by Django 2.1.2 on 2018-12-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='completionLevel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='evidenceMissing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='evidencePresent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='readiness',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
