# Generated by Django 2.1.2 on 2019-01-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='rubricLines',
        ),
        migrations.AddField(
            model_name='rubric',
            name='userSolution',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),
    ]
