# Generated by Django 2.1.2 on 2018-12-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricline',
            name='rubric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Rubric'),
            preserve_default=False,
        ),
    ]
