# Generated by Django 2.0.5 on 2018-11-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='criteria',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='rubrics.Criterion'),
            preserve_default=False,
        ),
    ]
