# Generated by Django 2.1.2 on 2018-12-05 17:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolution',
            name='solution',
            field=tinymce.models.HTMLField(),
        ),
    ]
