# Generated by Django 2.1.2 on 2019-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teaching Candidate'), (2, 'Clinical Supervisor'), (3, 'Challenge Coach'), (4, 'Admin')], null=True),
        ),
    ]
