# Generated by Django 2.1.2 on 2018-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_auto_20181204_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='completionLevel',
            field=models.IntegerField(default=0),
        ),
    ]
