# Generated by Django 2.1.2 on 2019-01-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_auto_20190117_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='challengeCompletionLevel',
            field=models.IntegerField(default=0),
        ),
    ]
