# Generated by Django 2.1.2 on 2018-11-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_auto_20181126_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
            preserve_default=False,
        ),
    ]
