# Generated by Django 2.1.2 on 2019-01-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0003_rubric_challengecompletionlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='competencies',
        ),
    ]
