# Generated by Django 2.1.2 on 2018-12-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_auto_20181128_1114'),
        ('rubrics', '0003_rubric_challenge'),
    ]

    operations = [
    ]
