# Generated by Django 2.1.2 on 2018-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0003_auto_20181205_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='completionLevel',
        ),
        migrations.RemoveField(
            model_name='rubricline',
            name='readiness',
        ),
        migrations.AddField(
            model_name='rubricline',
            name='completionLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
