# Generated by Django 2.0.5 on 2018-11-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0003_auto_20181105_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('learningObjs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective')),
            ],
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='learningObjs',
        ),
        migrations.AddField(
            model_name='challenge',
            name='competencies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Competency'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='competencies',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.Competency'),
            preserve_default=False,
        ),
    ]
