# Generated by Django 2.1.2 on 2018-12-04 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0004_merge_20181204_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidenceMissing', models.TextField()),
                ('evidencePresent', models.TextField()),
                ('feedback', models.TextField()),
                ('suggestions', models.TextField()),
                ('readiness', models.BooleanField()),
                ('learningObjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective')),
            ],
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='evidenceMissing',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='evidencePresent',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='feedback',
        ),
        migrations.AddField(
            model_name='rubric',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubricline',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Rubric'),
        ),
    ]
