# Generated by Django 2.1.2 on 2019-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_remove_rubric_competencies'),
    ]
