# Generated by Django 2.1.2 on 2019-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_remove_rubric_competencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='achievement',
            field=models.CharField(choices=[('A', 'Yes'), ('B', 'No'), ('C', 'Evidence for and against')], default='', max_length=1),
        ),
    ]
