# Generated by Django 2.1.2 on 2019-01-03 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_auto_20181212_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricline',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
