# Generated by Django 2.0.5 on 2018-11-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_auto_20181105_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='learningObjs',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='completionLevel',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='evidenceMissing',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='evidencePresent',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='feedback',
        ),
        migrations.AddField(
            model_name='criterion',
            name='learningObj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='completionLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='evidenceMissing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='evidencePresent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
