# Generated by Django 2.1.2 on 2018-12-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_auto_20181207_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjective',
            name='completionLevel',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='evidenceMissing',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='evidencePresent',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='readiness',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='suggestions',
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='completionLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='evidenceMissing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='evidencePresent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
