# Generated by Django 2.1.2 on 2018-12-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0005_auto_20181207_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricline',
            name='rubric',
        ),
        migrations.AddField(
            model_name='rubricline',
            name='solutionOwner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
            preserve_default=False,
        ),
    ]
