# Generated by Django 2.1.2 on 2019-01-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0005_criterion_achievement'),
    ]

