# Generated by Django 2.0.5 on 2018-11-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0006_learningobjective_competency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='competencies',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competency',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competency',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
