# Generated by Django 2.1.2 on 2018-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0006_usersolution_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='completionLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='evidenceMissing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='evidencePresent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='readiness',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='suggestions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
