# Generated by Django 2.0.5 on 2018-11-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0007_auto_20181105_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.TextField(),
        ),
    ]
