# Generated by Django 2.1.2 on 2019-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0007_remove_rubricline_criteria'),
    ]


