# Generated by Django 2.1.2 on 2019-01-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0008_rubricline_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('A', 'Yes'), ('B', 'No'), ('C', 'Evidence for and against')], default='', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='rubricline',
            name='criteria',
        ),
        migrations.AddField(
            model_name='criterialine',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Criterion'),
        ),
    ]
