# Generated by Django 2.0.5 on 2018-11-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0008_auto_20181105_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='competency',
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
            preserve_default=False,
        ),
    ]
