# Generated by Django 2.0.5 on 2018-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0009_auto_20181105_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjective',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='learningObjs',
            field=models.ManyToManyField(blank=True, to='rubrics.LearningObjective'),
        ),
    ]
