# Generated by Django 2.1.2 on 2019-01-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0010_criterialine_student'),
    ]

    operations = [

        migrations.AddField(
            model_name='criterialine',
            name='rubricLine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.RubricLine'),
            preserve_default=False,
        ),
    ]
