# Generated by Django 2.0.5 on 2018-11-06 15:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0010_auto_20181105_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='compGroup',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='compNumber',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='loNumber',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
