# Generated by Django 2.1.2 on 2019-02-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0011_auto_20190130_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='learningObjs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective'),
        ),
    ]
