# Generated by Django 2.1.7 on 2019-03-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0012_auto_20190212_1220'),
    ]

