# Generated by Django 2.1.7 on 2019-03-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0013_remove_rubric_rubriclines'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterialine',
            name='userSolution',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),


    ]
