# Generated by Django 2.0.5 on 2018-11-06 18:40

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0013_remove_learningobjective_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
