# Generated by Django 2.1.7 on 2019-03-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0014_criterialine_usersolution'),
    ]
