# Generated by Django 2.1.7 on 2019-03-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0016_auto_20190311_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterialine',
            name='rubricLine',
        ),
    ]
