# Generated by Django 2.1.7 on 2019-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0019_auto_20190319_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricline',
            name='ready',
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='needsLaterAttention',
            field=models.CharField(choices=[('A', 'Yes'), ('B', 'No')], default='B', max_length=1),
        ),
    ]
