# Generated by Django 2.1.7 on 2019-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0020_auto_20190319_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricline',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
