# Generated by Django 2.1.7 on 2019-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0021_rubricline_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolution',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
