# Generated by Django 2.1.7 on 2019-04-09 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0022_auto_20190322_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manualOverride', models.BooleanField(default=False)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Competency')),
                ('rubricLines', models.ManyToManyField(blank=True, to='rubrics.RubricLine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
