# Generated by Django 2.1.7 on 2019-04-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rubrics', '0024_auto_20190410_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAddendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('note', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('learningObjs', models.ManyToManyField(blank=True, to='rubrics.LearningObjective')),
                ('parentChallenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge')),
                ('userSolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution')),
            ],
        ),
        migrations.AddField(
            model_name='rubricline',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
