# Generated by Django 2.1.7 on 2019-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0025_auto_20190417_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricline',
            name='ready',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
