# Generated by Django 2.1.7 on 2019-04-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0026_auto_20190417_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricline',
            name='ignore',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
