# Generated by Django 2.1.7 on 2019-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0028_usersolution_customized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='learningObjs',
            field=models.ManyToManyField(blank=True, related_name='challenge', to='rubrics.LearningObjective'),
        ),
    ]
