# Generated by Django 2.1.7 on 2019-05-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0029_auto_20190510_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodTitle', models.TextField(blank=True, default='')),
                ('workFit', models.TextField(blank=True, default='')),
                ('proudDetail', models.TextField(blank=True, default='')),
                ('hardDetail', models.TextField(blank=True, default='')),
                ('objectiveWell', models.TextField(blank=True, default='')),
                ('objectivePoor', models.TextField(blank=True, default='')),
                ('personalLearningObjective', models.TextField(blank=True, default='')),
                ('userSolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution')),
            ],
        ),
    ]
