# Generated by Django 2.1.7 on 2019-05-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0031_auto_20190522_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackframe',
            name='userSolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),
    ]
