# Generated by Django 2.1.7 on 2019-05-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0032_feedbackframe_usersolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolution',
            name='goodTitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='hardDetail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='objectivePoor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='objectiveWell',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='personalLearningObjective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='proudDetail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='workFit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
