# Generated by Django 2.1.7 on 2019-05-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0033_auto_20190522_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackframe',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='feedbackframe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackframe',
            name='userSolution',
        ),
        migrations.DeleteModel(
            name='FeedbackFrame',
        ),
    ]
