# Generated by Django 2.1.7 on 2019-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0035_auto_20190522_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolution',
            name='changeLearningExp',
            field=models.TextField(blank=True, default='', verbose_name='What is one learning experience that you would change? How would you change it?'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='helpfulLearningExp',
            field=models.TextField(default='', verbose_name='Choose one of the above learning experiences that you found helpful. How did it help you?'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='notHelpfulLearningExp',
            field=models.TextField(default='', verbose_name="Choose one of the above learning experiences that was less helpful. Why wasn't it helpful?"),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='notIncludedLearningExp',
            field=models.TextField(blank=True, default='', verbose_name='Did you engage in any helpful learning experiences that were not included in the challenge guide? Please let us know what they were so that we can think about adding them.'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='goodTitle',
            field=models.TextField(blank=True, default='', verbose_name='What’s a good title for your work?'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='hardDetail',
            field=models.TextField(default='', verbose_name='Which detail shows what was especially hard for you?  how?'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='objectivePoor',
            field=models.TextField(blank=True, default='', verbose_name='What’s one objective that you still want to work on? What evidence leads you to think this is  an area of growth for you?'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='objectiveWell',
            field=models.TextField(blank=True, default='', verbose_name='What’s one objective that you met really well? What’s your evidence?'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='personalLearningObjective',
            field=models.TextField(blank=True, default='', verbose_name='Do you have any learning objectives of your own--in addition to those specified below--that you’d like the Observer to consider when they look at your work?  If so, add them at the top of the Observation Form.'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='proudDetail',
            field=models.TextField(default='', verbose_name='What’s a specific detail in this work that you are especially proud of? why?'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='workFit',
            field=models.TextField(default='', verbose_name='How does this piece of work fit into the story of your development as a teacher?'),
        ),
    ]
