# Generated by Django 2.1.7 on 2019-06-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0038_auto_20190603_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningExpoResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notApplicable', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('neutral', models.BooleanField(default=False)),
                ('positive', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge')),
            ],
        ),
    ]
