# Generated by Django 2.1.7 on 2019-06-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0039_learningexporesponses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningexporesponses',
            name='challenge',
        ),
        migrations.AddField(
            model_name='learningexporesponses',
            name='learningExperience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningExperience'),
        ),
    ]
