# Generated by Django 2.1.7 on 2019-06-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0040_auto_20190613_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningexporesponses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
