# Generated by Django 2.1.7 on 2019-06-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0041_learningexporesponses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningexporesponses',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='learningexporesponses',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='learningexporesponses',
            name='notApplicable',
        ),
        migrations.RemoveField(
            model_name='learningexporesponses',
            name='positive',
        ),
        migrations.AddField(
            model_name='learningexporesponses',
            name='learningExperienceResponse',
            field=models.CharField(choices=[(0, 'Not Applicable'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default='', max_length=2),
        ),
    ]
