# Generated by Django 2.1.7 on 2019-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0042_auto_20190620_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexporesponses',
            name='learningExperienceResponse',
            field=models.CharField(choices=[(0, 'Not Applicable'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default='', max_length=2, verbose_name='Response'),
        ),
    ]
