# Generated by Django 2.1.7 on 2019-06-24 16:18

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0043_auto_20190620_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='clinicalNeeds',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='degreeImplementation',
            field=models.CharField(choices=[(1, 'Design'), (2, 'Simulate'), (3, 'Implement')], default='', max_length=2, verbose_name='Degree of Implementation'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='scaleImplementation',
            field=models.CharField(choices=[(1, 'One on One'), (2, 'Small Group'), (3, 'Full Class')], default='', max_length=2, verbose_name='Scale of Implementation'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='standardSolution',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='typeImplementation',
            field=models.CharField(choices=[(1, 'Reflection'), (2, 'Classroom Evidence'), (3, 'Observation')], default='', max_length=2, verbose_name='Type of Evidence Required'),
        ),
    ]
