# Generated by Django 2.1.7 on 2019-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0044_auto_20190624_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challengeGroupChoices',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='Challenge Group'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='pullQuote',
            field=models.CharField(default='', max_length=500, verbose_name='Pull Quote'),
        ),
    ]
