# Generated by Django 2.1.7 on 2019-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0046_auto_20190624_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengeGroupChoices',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=2, verbose_name='Challenge Group'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='degreeImplementation',
            field=models.CharField(choices=[(1, 'Design'), (2, 'Simulate'), (3, 'Implement')], default=0, max_length=4, verbose_name='Degree of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scaleImplementation',
            field=models.CharField(choices=[(1, 'One on One'), (2, 'Small Group'), (3, 'Full Class')], default=0, max_length=4, verbose_name='Scale of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='typeImplementation',
            field=models.CharField(choices=[(1, 'Reflection'), (2, 'Classroom Evidence'), (3, 'Observation')], default=0, max_length=4, verbose_name='Type of Evidence Required'),
        ),
    ]
