# Generated by Django 2.1.7 on 2019-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0048_auto_20190624_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengeGroupChoices',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='Challenge Group'),
        ),
    ]
