# Generated by Django 2.1.7 on 2019-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0049_auto_20190624_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='degreeImplementation',
            field=models.CharField(choices=[(1, 'Design'), (2, 'Simulate'), (3, 'Implement')], default='', max_length=4, verbose_name='Degree of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scaleImplementation',
            field=models.CharField(choices=[(1, 'One on One'), (2, 'Small Group'), (3, 'Full Class')], default='', max_length=4, verbose_name='Scale of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='typeImplementation',
            field=models.CharField(choices=[(1, 'Reflection'), (2, 'Classroom Evidence'), (3, 'Observation')], default='', max_length=4, verbose_name='Type of Evidence Required'),
        ),
        migrations.AlterField(
            model_name='learningexporesponses',
            name='learningExperienceResponse',
            field=models.CharField(choices=[(0, 'Not Applicable'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default='', max_length=2, verbose_name='Response'),
        ),
    ]
