# Generated by Django 2.1.7 on 2019-06-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0050_auto_20190624_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexporesponses',
            name='learningExperienceResponse',
            field=models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Negative'), ('2', 'Neutral'), ('3', 'Positive')], default='', max_length=2, verbose_name='Response'),
        ),
    ]
