# Generated by Django 2.1.7 on 2019-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0052_auto_20190625_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='degreeImplementation',
            field=models.CharField(choices=[(1, 'Design'), (2, 'Simulate'), (3, 'Implement')], default='', max_length=4, verbose_name='Degree of Implementation'),
        ),
    ]
