# Generated by Django 2.1.7 on 2019-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0057_auto_20190625_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='degreeImplementation',
            field=models.IntegerField(choices=[(1, 'Design'), (2, 'Simulate'), (3, 'Implement')], default=1, verbose_name='Degree of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scaleImplementation',
            field=models.IntegerField(choices=[(1, 'One on One'), (2, 'Small Group'), (3, 'Full Class')], default=1, verbose_name='Scale of Implementation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='typeImplementation',
            field=models.IntegerField(choices=[(1, 'Reflection'), (2, 'Classroom Evidence'), (3, 'Observation')], default=1, verbose_name='Type of Implementation'),
        ),
    ]
