# Generated by Django 2.1.7 on 2019-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0058_auto_20190625_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningexperience',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
    ]
