# Generated by Django 2.1.7 on 2019-06-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0059_learningexperience_index'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='learningexperience',
            order_with_respect_to='challenge',
        ),
    ]
