# Generated by Django 2.1.7 on 2019-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0060_auto_20190626_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolution',
            name='hardDetail',
            field=models.TextField(default='', verbose_name='Which detail shows what was especially hard for you?  how? (*required)'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='helpfulLearningExp',
            field=models.TextField(default='', verbose_name='Choose one of the above learning experiences that you found helpful. How did it help you? (*required)'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='notHelpfulLearningExp',
            field=models.TextField(default='', verbose_name="Choose one of the above learning experiences that was less helpful. Why wasn't it helpful? (*required)"),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='proudDetail',
            field=models.TextField(default='', verbose_name='What’s a specific detail in this work that you are especially proud of? why? (*required)'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='workFit',
            field=models.TextField(default='', verbose_name='How does this piece of work fit into the story of your development as a teacher? (*required)'),
        ),
    ]
