# Generated by Django 2.1.7 on 2019-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0063_auto_20190722_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='CLASSROOMEVIDENCE',
            field=models.BooleanField(default=False, verbose_name='Classroom Evidence'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='DESIGN',
            field=models.BooleanField(default=False, verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='FULLCLASS',
            field=models.BooleanField(default=False, verbose_name='Full Class'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='IMPLEMENT',
            field=models.BooleanField(default=False, verbose_name='Implement'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='OBSERVATION',
            field=models.BooleanField(default=False, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='ONEONONE',
            field=models.BooleanField(default=False, verbose_name='One on One'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='REFLECTION',
            field=models.BooleanField(default=False, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='SIMULATE',
            field=models.BooleanField(default=False, verbose_name='Simulate'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='SMALLGROUP',
            field=models.BooleanField(default=False, verbose_name='Small Group'),
        ),
    ]
