# Generated by Django 2.1.7 on 2019-07-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0065_auto_20190724_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterialine',
            name='achievement',
            field=models.CharField(choices=[('No Response', '--'), ('A', 'Yes'), ('B', 'No'), ('C', 'Evidence for and against')], default='', max_length=1),
        ),
    ]
