# Generated by Django 2.1.7 on 2019-08-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0068_auto_20190730_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.BooleanField(default=False)),
                ('rubricLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.RubricLine')),
            ],
        ),
        migrations.AlterModelOptions(
            name='learningexperience',
            options={'ordering': ['challenge']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='learningexperience',
            order_with_respect_to=None,
        ),
    ]
