# Generated by Django 2.1.7 on 2019-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0069_auto_20190816_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
