# Generated by Django 2.1.7 on 2019-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0070_coachreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolution',
            name='solution',
            field=models.TextField(default=''),
        ),
    ]
