# Generated by Django 2.1.7 on 2019-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0071_auto_20190821_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexperience',
            name='learningObjectives',
            field=models.ManyToManyField(blank=True, related_name='learningExpo', to='rubrics.LearningObjective'),
        ),
    ]
