# Generated by Django 2.1.7 on 2019-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0072_auto_20190821_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Show Challenge'),
        ),
    ]
