# Generated by Django 2.1.7 on 2019-09-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0074_auto_20190903_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningObjectives', models.ManyToManyField(blank=True, to='rubrics.LearningObjective')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='rubrics.SolutionInstance'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='solutionInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance'),
        ),
    ]
