# Generated by Django 2.1.7 on 2019-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0075_auto_20190903_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
