# Generated by Django 2.1.7 on 2019-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0076_solutioninstance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutioninstance',
            name='learningObjectives',
            field=models.ManyToManyField(blank=True, null=True, to='rubrics.LearningObjective'),
        ),
    ]
