# Generated by Django 2.1.7 on 2019-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0077_auto_20190903_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutioninstance',
            name='learningObjectives',
            field=models.ManyToManyField(blank=True, to='rubrics.LearningObjective'),
        ),
    ]
