# Generated by Django 2.1.7 on 2019-09-05 15:12

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0080_auto_20190903_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='prompt',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Solution Prompt'),
        ),
    ]
