# Generated by Django 2.2.5 on 2019-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0081_solutioninstance_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
