# Generated by Django 2.2.5 on 2019-09-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0082_megachallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='megaChallenge',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.MegaChallenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='overRide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='mega_challenge_that_owns_me', to='rubrics.SolutionInstance'),
        ),
    ]
