# Generated by Django 2.2.5 on 2019-09-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0083_auto_20190913_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='pullQuote',
            field=models.CharField(default='', max_length=1000, verbose_name='Pull Quote'),
        ),
    ]
