# Generated by Django 2.2.5 on 2019-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0086_auto_20190918_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexporesponses',
            name='learningExperienceResponse',
            field=models.CharField(choices=[('4', '-'), ('0', 'Not Applicable'), ('1', 'Negative'), ('2', 'Neutral'), ('3', 'Positive')], default='', max_length=2, verbose_name='Response'),
        ),
    ]
