# Generated by Django 2.2.5 on 2019-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0087_auto_20190918_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachreview',
            name='evaluator',
            field=models.ManyToManyField(blank=True, to='rubrics.Evaluated'),
        ),
    ]
