# Generated by Django 2.2.5 on 2019-09-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0088_coachreview_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachreview',
            name='evaluator',
        ),
        migrations.AddField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
