# Generated by Django 2.2.5 on 2019-09-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0089_auto_20190923_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
