# Generated by Django 2.2.5 on 2019-09-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0090_auto_20190923_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.Evaluated'),
        ),
    ]
