# Generated by Django 2.2.5 on 2019-09-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0091_auto_20190923_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachreview',
            name='dateEvaluated',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='dateEval', to='rubrics.Evaluated'),
        ),
        migrations.AlterField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rubrics.Evaluated'),
        ),
    ]
