# Generated by Django 2.2.5 on 2019-09-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0093_auto_20190923_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachreview',
            name='dateEvaluated',
        ),
        migrations.AlterField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='rubrics.Evaluated'),
        ),
        migrations.AlterField(
            model_name='evaluated',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
