# Generated by Django 2.2.5 on 2019-09-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0094_auto_20190923_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachreview',
            name='evaluator',
        ),
    ]
