# Generated by Django 2.2.5 on 2019-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0095_remove_coachreview_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricline',
            name='evaluated',
            field=models.ManyToManyField(blank=True, related_name='rubricLine_evaluated', to='rubrics.Evaluated'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='evaluated',
            field=models.ManyToManyField(blank=True, related_name='evaluated', to='rubrics.Evaluated'),
        ),
    ]
