# Generated by Django 2.2.5 on 2019-09-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0096_auto_20190930_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricline',
            name='evaluated',
        ),
        migrations.AddField(
            model_name='rubricline',
            name='evaluated',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.Evaluated'),
        ),
    ]
