# Generated by Django 2.2.5 on 2019-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0097_auto_20190930_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
