# Generated by Django 2.2.5 on 2019-10-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0098_auto_20191001_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachreview',
            name='evaluator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='rubrics.Evaluated'),
        ),
    ]
