# Generated by Django 2.2.5 on 2019-10-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0100_auto_20191008_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterialine',
            name='evaluator',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteriaLine_evaluator', to='rubrics.Evaluated'),
        ),
        migrations.AlterField(
            model_name='rubricline',
            name='evaluated',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Evaluated'),
        ),
    ]
