# Generated by Django 2.2.5 on 2019-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0101_auto_20191015_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(default='', upload_to='uploads/challenges/', width_field='200px'),
        ),
    ]
