# Generated by Django 2.2.5 on 2019-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0102_challenge_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(blank=True, default='', height_field='60px', upload_to='uploads/challenges/'),
        ),
    ]
