# Generated by Django 2.2.5 on 2019-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0103_auto_20191029_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(blank=True, default='', height_field='height', upload_to='uploads/challenges/'),
        ),
    ]
