# Generated by Django 2.2.5 on 2019-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0104_auto_20191029_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
