# Generated by Django 2.2.5 on 2019-12-02 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0105_challenge_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachreview',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='coachreview',
            name='rubricLine',
        ),
        migrations.AddField(
            model_name='coachreview',
            name='userSolution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.UserSolution'),
        ),
        migrations.AlterField(
            model_name='evaluated',
            name='whoEvaluated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
