# Generated by Django 2.2.5 on 2019-12-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0107_auto_20191206_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningexperience',
            options={'ordering': ['index']},
        ),
    ]
