# Generated by Django 2.2.5 on 2019-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0108_auto_20191206_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
