# Generated by Django 2.2.5 on 2019-12-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0109_solutioninstance_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutioninstance',
            name='order',
        ),
        migrations.CreateModel(
            name='ChallengeSolutionJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge')),
                ('solutionInstance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance')),
            ],
        ),
    ]
