# Generated by Django 2.2.5 on 2019-12-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0110_auto_20191209_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengesolutionjunction',
            options={'ordering': ('order',)},
        ),
    ]
