# Generated by Django 2.2.5 on 2019-12-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0111_auto_20191209_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
