# Generated by Django 2.2.5 on 2020-01-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0112_solutioninstance_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipFile', models.FileField(upload_to='resources')),
                ('challenge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge')),
            ],
        ),
    ]
