# Generated by Django 2.2.5 on 2020-01-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0113_challengeresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreview',
            name='userSolution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coachReview', to='rubrics.UserSolution'),
        ),
    ]
