# Generated by Django 2.2.5 on 2020-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0114_auto_20200114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive (hides LO)'),
        ),
    ]
