# Generated by Django 2.2.5 on 2020-01-27 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0115_learningobjective_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeresources',
            name='zipFile',
        ),
        migrations.AddField(
            model_name='challengeresources',
            name='fileContainer',
            field=models.FileField(default='', upload_to='resources/'),
        ),
        migrations.CreateModel(
            name='ChallengeResourcesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources/')),
                ('challengeResources', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resource_file', to='rubrics.ChallengeResources')),
            ],
        ),
    ]
