# Generated by Django 2.2.5 on 2020-01-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0116_auto_20200127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresourcesfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
