# Generated by Django 2.2.5 on 2020-01-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0117_auto_20200128_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresourcesfile',
            name='file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
