# Generated by Django 2.2.5 on 2020-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0118_auto_20200128_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresourcesfile',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
