# Generated by Django 2.2.5 on 2020-01-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0120_auto_20200130_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresources',
            name='learningExperience',
            field=models.ManyToManyField(blank=True, null=True, to='rubrics.LearningExperience'),
        ),
        migrations.AddField(
            model_name='challengeresources',
            name='megaChallenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubrics.MegaChallenge'),
        ),
        migrations.AlterField(
            model_name='challengeresources',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubrics.Challenge'),
        ),
    ]
