# Generated by Django 2.2.5 on 2020-02-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0121_auto_20200130_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexperience',
            name='challenge',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.Challenge'),
        ),
    ]
