# Generated by Django 2.2.5 on 2020-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0122_auto_20200205_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresources',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
