# Generated by Django 2.2.5 on 2020-02-19 16:57

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0125_auto_20200218_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresources',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
