# Generated by Django 2.2.5 on 2020-02-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0126_challengeresources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresourcesfile',
            name='file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
