# Generated by Django 2.2.5 on 2020-02-20 22:32

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0128_auto_20200219_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresources',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challengeresources',
            name='fileContainer',
            field=models.FileField(blank=True, default='', upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='challengeresources',
            name='learningExperience',
            field=models.ManyToManyField(blank=True, to='rubrics.LearningExperience'),
        ),
        migrations.AlterField(
            model_name='challengeresourcesfile',
            name='challengeResources',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='resource_file', to='rubrics.ChallengeResources'),
        ),
    ]
