# Generated by Django 2.2.5 on 2020-02-20 22:32

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0129_auto_20200220_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresources',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, default=''),
        ),
    ]
