# Generated by Django 2.2.5 on 2020-02-21 18:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0130_auto_20200220_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='newDesc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
