# Generated by Django 2.2.5 on 2020-02-21 19:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0131_challenge_newdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='newDesc',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Challenge Overview'),
        ),
    ]
