# Generated by Django 2.2.5 on 2020-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0132_auto_20200221_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='megachallenge',
            name='challengeGroupChoices',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='Challenge Group'),
        ),
    ]
