# Generated by Django 2.2.5 on 2020-02-27 20:24

import ckeditor_uploader.fields
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0133_megachallenge_challengegroupchoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='CLASSROOMEVIDENCE',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='DESIGN',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='FULLCLASS',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='IMPLEMENT',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='OBSERVATION',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='ONEONONE',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='REFLECTION',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='SIMULATE',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='SMALLGROUP',
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='clinicalNeeds',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Clinical Needs'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Challenge Overview'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='picture',
            field=models.ImageField(blank=True, default='', height_field='height', upload_to='uploads/challenges/'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='pullQuote',
            field=models.CharField(default='', max_length=1000, verbose_name='Pull Quote'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='standardSolution',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Standard Solution'),
        ),
    ]
