# Generated by Django 2.2.5 on 2020-03-02 17:32

import ckeditor_uploader.fields
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0135_megachallenge_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningexperience',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='megachallenge',
            name='clinicalNeeds',
            field=djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Clinical Needs'),
        ),
        migrations.AlterField(
            model_name='megachallenge',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Challenge Overview'),
        ),
        migrations.AlterField(
            model_name='megachallenge',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='megachallenge',
            name='pullQuote',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Pull Quote'),
        ),
        migrations.AlterField(
            model_name='megachallenge',
            name='standardSolution',
            field=djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Standard Solution'),
        ),
    ]
