# Generated by Django 2.2.5 on 2020-06-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0136_auto_20200302_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreview',
            name='release',
            field=models.BooleanField(default=False, verbose_name='Release to TC?'),
        ),
    ]
