# Generated by Django 2.2.5 on 2020-07-09 18:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0138_usersolution_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='specialized',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='TfJSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField()),
                ('learningObjectives', models.ManyToManyField(blank=True, to='rubrics.LearningObjective')),
                ('solutionInstance', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
