# Generated by Django 2.2.5 on 2020-07-20 15:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0139_auto_20200709_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='TfJQuestionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('response', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='TfJEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningObjective', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective')),
                ('question', models.ManyToManyField(blank=True, to='rubrics.TfJQuestionField')),
            ],
        ),
    ]
