# Generated by Django 2.2.5 on 2020-07-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0140_tfjeval_tfjquestionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfjeval',
            name='userSolution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.TfJSolution'),
        ),
    ]
