# Generated by Django 2.2.5 on 2020-07-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0143_auto_20200720_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfjsolution',
            name='learningObjectives',
        ),
        migrations.AddField(
            model_name='tfjsolution',
            name='coachLO',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coachLO', to='rubrics.LearningObjective'),
        ),
        migrations.AddField(
            model_name='tfjsolution',
            name='tcLO',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective'),
        ),
    ]
