# Generated by Django 2.2.5 on 2020-08-21 16:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0145_auto_20200803_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='drivingQ',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Driving Questions'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='soldThemes',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='SoLD Themes'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tfjFocus',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Teaching for Justice Focus'),
        ),
    ]
