# Generated by Django 2.2.5 on 2020-08-21 16:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0148_auto_20200821_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='drivingQ',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='soldThemes',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='tfjFocus',
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='drivingQ',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Driving Questions'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='soldThemes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='SoLD Themes'),
        ),
        migrations.AddField(
            model_name='megachallenge',
            name='tfjFocus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Teaching for Justice Focus'),
        ),
    ]
