# Generated by Django 2.2.5 on 2021-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0149_auto_20200821_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='archive',
            field=models.BooleanField(default=True),
        ),
    ]
