# Generated by Django 2.2.5 on 2021-08-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0152_megachallenge_collapse'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluated', models.ManyToManyField(blank=True, related_name='evaluator', to='rubrics.Evaluated')),
                ('solutionInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rubrics.SolutionInstance')),
            ],
        ),
        migrations.CreateModel(
            name='TempUserSolution',
            fields=[
                ('generalsolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rubrics.GeneralSolution')),
                ('solution', djrichtextfield.models.RichTextField()),
                ('archived', models.BooleanField(default=False)),
                ('goodTitle', models.TextField(blank=True, default='', verbose_name='What’s a good title for your work?')),
                ('workFit', models.TextField(default='', verbose_name='How does this piece of work fit into the story of your development as a teacher? (*required)')),
                ('proudDetail', models.TextField(default='', verbose_name='What’s a specific detail in this work that you are especially proud of? why? (*required)')),
                ('hardDetail', models.TextField(default='', verbose_name='Which detail shows what was especially hard for you?  how? (*required)')),
                ('objectiveWell', models.TextField(blank=True, default='', verbose_name='What’s one objective that you met really well? What’s your evidence?')),
                ('objectivePoor', models.TextField(blank=True, default='', verbose_name='What’s one objective that you still want to work on? What evidence leads you to think this is  an area of growth for you?')),
                ('personalLearningObjective', models.TextField(blank=True, default='', verbose_name='Do you have any learning objectives of your own--in addition to those specified below--that you’d like the Observer to consider when they look at your work?  If so, add them at the top of the Observation Form.')),
                ('helpfulLearningExp', models.TextField(default='', verbose_name='Choose one of the above learning experiences that you found helpful. How did it help you? (*required)')),
                ('notHelpfulLearningExp', models.TextField(default='', verbose_name="Choose one of the above learning experiences that was less helpful. Why wasn't it helpful? (*required)")),
                ('changeLearningExp', models.TextField(blank=True, default='', verbose_name='What is one learning experience that you would change? How would you change it?')),
                ('notIncludedLearningExp', models.TextField(blank=True, default='', verbose_name='Did you engage in any helpful learning experiences that were not included in the challenge guide? Please let us know what they were so that we can think about adding them.')),
                ('customized', models.BooleanField(default=False)),
            ],
            bases=('rubrics.generalsolution',),
        ),
    ]
