# Generated by Django 2.2.5 on 2021-08-24 18:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0153_generalsolution_tempusersolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTfJSolution',
            fields=[
                ('generalsolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rubrics.GeneralSolution')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField()),
                ('coachLO', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='TempCoachLO', to='rubrics.LearningObjective')),
                ('tcLO', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rubrics.LearningObjective')),
            ],
            bases=('rubrics.generalsolution',),
        ),
    ]
